# Generated by Django 5.1.3 on 2024-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
     model_name='passenger',
     name='flight',
     field=models.ForeignKey(on_delete=models.CASCADE, to='app.Flight'),
     ),

        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='flight_tickets', to='app.passenger'),
        ),
    ]
